# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
    python: "mambaforge-4.10"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: devtools/conda-envs/docs_env.yaml
