name: Check for API breaks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Check for API breaks
      continue-on-error: true
      run: |
        pip install griffe
        pip install -e .
        griffe check "openff.interchange" --verbose
