name: nightly tests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      CI_OS: ${{ matrix.os }}
      PYVER: ${{ matrix.python-version }}
      COV: --cov=openff/system --cov-report=xml --cov-config=setup.cfg --cov-append

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: devtools/conda-envs/test_env.yaml
        auto-activate-base: false

    - name: Install development version of OpenFF Recharge
      shell: bash -l {0}
      run: |
        mamba install --only-deps openff-recharge -c conda-forge -c omnia
        python -m pip install git+https://github.com/openforcefield/openff-recharge.git

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install package
      shell: bash -l {0}
      run: |
        python setup.py develop --no-deps

    - name: Install OpenFF Units
      shell: bash -l {0}
      run: |
        pip install git+git://github.com/mattwthompson/openff-units.git

    - name: Clone ParmEd tests
      shell: bash -l {0}
      run: |
        git clone https://github.com/parmed/tests
        cp -r tests/pmdtest .
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run mypy
      continue-on-error: true
      shell: bash -l {0}
      run: |
        mypy --show-error-codes --namespace-packages -p "openff.system"

    - name: Run unit tests
      if: always()
      shell: bash -l {0}
      run: |
        python -m pytest -v $COV openff/system/tests/ --ignore=openff/system/tests/parmed/

    - name: Run ParmEd tests
      continue-on-error: true
      shell: bash -l {0}
      run: |
        python -m pytest -v $COV openff/system/tests/parmed

    - name: Run example notebooks
      shell: bash -l {0}
      run: |
        python -m pytest -v $COV examples/ --nbval-lax

    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
